### ISSUE TITLE
Add instructions for Git GUI/Bash

### ISSUE THREAD

**Issue by jandresgannon** [rexdouglass/MSSLStyleGuide#4]
Add links to install Git GUI/Bash proper to the instructions and how that has to be linked in RStudio for projects (what @rexdouglass and @tlscherer covered with me in December)

**Comment by tlscherer** [comment]
Good catch! Added to the "Git and Github" section on https://rexdouglass.github.io/MSSLStyleGuide/01_Workstation_Setup.nb.html.
